name: xfer-relearn
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - pyarrow
  - scikit-learn
  - pyyaml
  - tqdm
  - pytest
  - pip:
      - accelerate
      - datasets
      - huggingface_hub
      - "lm-eval @ git+https://github.com/EleutherAI/lm-evaluation-harness.git@6d642546f4688648fced259eb3302efd36ece5af"
      - mwparserfromhell==0.7.2
      - mwxml==0.3.8
      - transformers
